### ISSUE TITLE
Option to automatically disable overlay when it's not looked at for performance boost

### ISSUE THREAD

**Issue by tapanij** [Hotrian/OVRdrop-Public#18]
For example if the overlay is behind a controller most of the time, then there's no reason to do capturing.

**Comment by Hotrian** [comment]
I tested this on my main system and it didn't seem to make much of any difference. GPU usage stayed the same with or without the Overlay/Capture, frame timings stayed the same.

It actually hurt performance in `Unlimited` because Unity wasn't being held back by the Capture API and updated as fast as possible, up to around 500FPS, using about 20% of my CPU. With the FPS locked at 60FPS it only uses about 4% of my CPU, and when being held back by the Capture API it uses about 12% in `Unlimited`.

Does OVRdrop significantly affect performance for you? What is your PC specs?

I will test again on my old system (FX-6300, 2x R7 265, literally scores 0 in SteamVR Performance Test) when I have a chance. I suspect it will make a difference on that PC, but that PC is way below spec for VR.

**Comment by tapanij** [comment]
Nah it's actually fine on my pc, 6700k gtx970. I came up with the idea before I checked the CPU usage.

**Comment by Hotrian** [comment]
This has actually been implemented for a long time at this point. Unfortunately I'm not sure which build off the top of my head solved this issue.

My implementation was to disable the capture methods when the HMD is at an angle that would prevent it from ever seeing the screen. This hasn't seemed to cause any issues except for `Screen Space Overlay Won't Refresh` issue which popped up [a few times](https://steamcommunity.com/app/586210/discussions/0/1368380934244112587/) on our Steam community forums, and was fixed in [v1.0.5p13](https://steamcommunity.com/app/586210/discussions/2/1697168437866221988/#c1697168437867368643), which hasn't been pushed to the publicly listed builds yet, but can be accessed through Steam [using this guide](https://github.com/Hotrian/OVRdrop-Public/wiki/Accessing-Alternative-Builds) for anyone interested.

The remaining overhead from SteamVR maintaining the Overlay is extremely marginal, and has been left at this time to prevent really-quick head movements from exposing an Overlay "pop in".

Therefore, I am closing this issue at this time. I believe this functionality is currently missing from the 'main' build, but I believe it exists as far downstream as the `experimental_2` branch, and if it doesn't, then it will be pushed there shortly.
