### ISSUE TITLE
Steam always says OVRdrop is running

### ISSUE THREAD

**Issue by rjSampaio** [Hotrian/OVRdrop-Public#33]
after i close OVRdrop and the windows closes, steam still says its running, i cant close steam because it still says OVRdrop running and is gona try to close it, cant,, and then tells me to close it.

I cant even find OVRdrop.exe in the taskmanager.

Because of this i cant even reopen, since is already "running"

**Comment by Hotrian** [comment]
Steam has a bug where it considers anything a game opens to be part of that game. Is it possible OVRdrop started SteamVR, Steam itself, or maybe some other application? Steam will consider that application to be part of OVRdrop as well.

**Comment by Hotrian** [comment]
You never responded so I'm going to assume you fixed the issue.

I notice Steam will continue to say OVRdrop is running if you start OVRdrop before SteamVR is running - then it will say you are in OVRdrop until you close SteamVR. I'm assuming this is what happened to you. Because of this, I always start SteamVR before starting OVRdrop.
