### ISSUE TITLE
Frames per second

### ISSUE THREAD

**Issue by noel4nopun** [Hotrian/OVRdrop-Public#39]
I am getting a significant drop in frame rate when launching OVR, I am using it in the iracing motorsports simulator, with the oVR off I get the maximum 89 frames per second but as soon as I launch OVR it drops to a staggering un usable frame rate of 45, and this is when I am the only car on the track I would hate to see what would happen in an official race with 20 other cars in the sim.

I have tried a variety of frame rate settings in OVR but cant seem to figure out what I need to do to get back to my desired 89 frames per second, also if you don't mind I have another question, I have saved a profile but every-time it launches it defaults to ovr drop as the source whereas I would like it to be monitor 2, if I cant fix the frame rate issue a possible work around would be to turn off OVR when I dont need it, but while racing I can't change the setting to monitor 2

Other than these issues this is an amazing app, I cant believe I can load dashboard apps in VR, now if I can just get up to 89 fps

**Comment by Hotrian** [comment]
What system specs?

What HMD?

> I get the maximum 89 frames per second

You should be getting at least 90 FPS to keep up with SteamVR. Can you post a copy of your frame timings before and after OVRdrop launches?

Unfortunately there probably isn't much that can be done here. OVRdrop itself is very light on resources and there isn't much of anything that can be cut down. The issue here is likely with iRacing, have you tried using other games?

Have you tried turning the Capture Rate down? That's the FPS dropdown in the top left. The "FPS" read out in OVRdrop is the FPS of the window and not the capture rate.

**Comment by noel4nopun** [comment]
210-ADHC	Area 51 Base
 Hide itemized list
1	370-ABWP	16GB Quad Channel DDR4 at 2133MHz
1	580-AAOJ	Alienware Standard USB 2.0 Keyboard (English)
1	490-BDGN	NVIDIA GeForce GTX 970 with 4GB GDDR5 - PNY
1	658-BCKI	7260 AC Driver
1	400-AFOO	256GB SSD 6Gb/s Main + 4TB 5400RPM SATA 6Gb/s Storage
1	619-AHCY	Windows 10 Home-HE (64bit) English
1	570-AACL	Alienware USB Optical Mouse
1	429-AAMV	Slot-Loading Dual Layer DVD Reader
1	555-BCFD	Intel(R) Dual Band Wireless-AC 7260 @ 5GHz + Bluetooth
1	450-AEDB	Power Cord, 1500W
1	340-AGUD	Safety/Environment and Regulatory Guide (English/French)
1	801-1893	Dell Limited Hardware Warranty Plus Service
1	803-2446	Premium Support, 1 Year
1	803-2439	Premium Support with Onsite Service After Remote Diagnosis, 1 Year
1	338-BKFD	Intel(R) Core(TM) i7-6800K Processor (6-cores, 15MB Cache, Turbo Boost Max 3.0, Overclocked up to 4.0 GHz)
1	321-BCHF	Alienware(TM) 1500 Watt Multi-GPU Approved Power Supply
1	340-ACUM	System BOOT for Windows, AW51
1	340-ANMJ	Resource DVD W7/W8.1
1	658-BBTV	Cyberlink Media Suite Essentials for Windows without Media
1	525-0016	Dropbox, Digital Delivery, 20GB for 1 year Promotion
1	389-BFSN	Regulatory Label, 1500W
1	338-BDFP	Intel(R) Core(TM) I7 CPU Label
1	340-ALTG	Ship Group,ANW-DT,Dell Americas Organization,CENTAURI
1	340-AMZI	Placemat (English,French,BRPT,Spanish)
1	332-0550	Dell.com Order
1	332-1286	US Order
1	332-1530	Dell.com Order
1	340-ALTH	Shipping Material
1	658-BCUO	Additional Software
1	340-ACQQ	No Option Included
1	817-BBBB	No FGA
1	658-BCSC	Microsoft Office 30 Day Trial
1	817-BBBP	None Included

**Comment by noel4nopun** [comment]
thanks for responding I am at work and not at the machine I have sent a copy of my DxDiag file to 
Nicholas Ewalt in the past but cant seem to locate the attachment.

I don't really use any other game so I'd love to see if I could get this going smoother, I have tried the FPS from the top left pull down, to different degrees of success, 39 droped to almost 14 fps in the sim, whereas 90 was staying at 45 fps and unlimited in OVR said 400 something FPS, but inside the sim I was still at 45 fps, is there another area I can play with the FPS?

**Comment by noel4nopun** [comment]
found it! 
[DxDiag.txt](https://github.com/Hotrian/OVRdrop-Public/files/1095981/DxDiag.txt)

**Comment by Hotrian** [comment]
I just remembered you gave me a DxDiag [here](https://github.com/Hotrian/OVRdrop-Public/issues/36#issuecomment-300639196) - I assume it's still the same PC and you are still using a Vive?

> I have tried the FPS from the top left pull down, to different degrees of success, 39 droped to almost 14 fps in the sim, whereas 90 was staying at 45 fps and unlimited in OVR said 400 something FPS, but inside the sim I was still at 45 fps

This sounds like maybe you're using an older version?

> 39 droped to almost 14 fps in the sim

Do you mean 30 here? When you set OVRdrop's FPS to 30fps, iRacing went to 14 fps? That definitely shouldn't be happening. iRacing should get faster if you slow OVRdrop down, not the other way around.

> unlimited in OVR said 400 something FPS, but inside the sim I was still at 45 fps

This just controls how quickly OVRdrop is trying to update the Overlay. I wouldn't set it to `Unlimited` because it is taking a screenshot every few milliseconds, which could actually slow down SteamVR. If you set OVRdrop to 24 FPS though, OVRdrop should report that it is capturing at about 24 FPS, and SteamVR should be running at 90 FPS as intended.

If you could get me a screenshot of the frame timings before and after OVRdrop is running, and also a screenshot of OVRdrop's main window, that would be a huge help :).

**Comment by noel4nopun** [comment]
fantastic, I will, wrapping up work in a couple of hours and will post my findings thank you so much for your help and I hope I am able to trouble shoot this, I fear there are a tremendous amount of variables involved, between the PC, Vive, Steam and Iracing I am sure something somewhere is misconfigured, I may be mistaken But I believe about a month ago I was running everything as it should at the ideal 89 fps, but cant confirm that nor know what would have changed to make it no longer work

**Comment by noel4nopun** [comment]
Sorry to have bothered you I did some test again today and it seems to be working as expected.
The knowing the lower the refresh rate rather than going to unlimited helped in confirming the settings, I believe this issue has been resolved and you could mark the case closed, thank you so much for your help and shhh on letting the other drivers knowing you can use your app to do what I am doing, this is such an advantage over all of the other iracers!

**Comment by Hotrian** [comment]
Glad to hear it seems to be working again :). Let me know if anything changes!
