### ISSUE TITLE
Add Simplified Chinese support?

### ISSUE THREAD

**Issue by Sonic853** [Hotrian/OVRdrop-Public#54]
I can provide some translation support if you can.

**Comment by Hotrian** [comment]
I still plan to add translation support but the Unity UI is quite complex and it will still be a while before I can add support for other languages. Currently everything is in English. I will keep you in mind for when I am ready to add translation support :). Thanks for the offer.

**Comment by Sonic853** [comment]
understood 👌

**Comment by Hotrian** [comment]
Okay I have most of the UI text and buttons as well as tooltips ready for translation if you've got some free time.

I've added a new build to Steam, `v1.0.5q31` (access code: `8XYQFsu9qfsE`). Switch over to this branch [as mentioned here](https://github.com/Hotrian/OVRdrop-Public/wiki/Accessing-Alternative-Builds). Once you are on v1.0.5q31 navigate to `C:\Program Files (x86)\Steam\steamapps\common\OVRdrop\OVRdrop_Data\StreamingAssets\Translations\` (unless you have moved your Steam library, in which case navigate accordingly), where you will find a `Chinese.xml` file, which is the Chinese translation file. This is an XML file, so you can ignore anything inside `< >` tags. For example, on Line 3 you have `<QuickAccessTitle>OVRdrop Settings Quick Access</QuickAccessTitle>`, in which case you would ignore the XML tags and just translate `OVRdrop Settings Quick Access`. You can also ignore `{b}` and `{/b}` which are for bolded text, and `[{0}]` which is used to insert the correct Hotkey on the applicable tooltips, just preserve them as is. I would recommend editing this in [Notepad++](https://notepad-plus-plus.org/) just because it will make it a bit prettier and easier to edit.

In `v1.0.5q31`, you will find a new Language Selection panel on the left side (seen [here](https://i.imgur.com/RE8qfoQ.png)). Click on the Chinese flag which will load the "Chinese" translation (right now it will appear the same as the English version). Open up the Chinese.xml as mentioned above, make a change, save the file, then press the [reload button](https://i.imgur.com/mdJ5hgh.png) which will automatically refresh the current translation, and should show your changes. This will let you test the translation for fit. If you absolutely cannot make something fit, just do what you can and I'll adjust the UI to fit.

You will notice that the Chinese translation file has a lot of blank lines. Please preserve these blank lines as they are used internally for formatting purposes.

You will also note the German and French flags are clickable. The German translation is nearly complete, although is missing tooltips and a few of OVRdrop's menus which do not currently have translation support. The French translation is mostly incomplete. Don't mind these as they are also works in progress :).

Please be careful to keep a backup of the `Chinese.xml` file as you work, as Steam may delete or overwrite it if you switch branches or Verify the integrity of OVRdrop's files.

I assume not everything will have a perfect translation so feel free to consult with me on any issues. You can always [join us on Discord](https://discord.gg/uJDs4Q9) for quicker responses.

If you don't feel up to translating the whole thing, any bit you can do is a huge help :). Thanks again for the offer :).
