### ISSUE TITLE
FPS limit under 60 doesn't work

### ISSUE THREAD

**Issue by TrashJager** [Hotrian/OVRdrop-Public#81]
FPS limit under 60 doesn't seem to work. When the limiter is set to anything under 60 it will still render 60,

Using a Pimax 5K Super in 90HZ mode. Refresh rate doesn't seem to affect the limiter as whenever I go to 180hz it's still the same.

**Comment by Hotrian** [comment]
If I recall correctly, the application will always report at least 60fps since this is required to make the overlay move around smoothly in VR, but the actual capture rate will go below 60. Try setting it to something very low and watching a video, and you should notice the capture rate itself is lowered.
